from langchain_groq import ChatGroq
from config import GROQ_API_KEY, MODEL_NAME

llm = ChatGroq(
    model=MODEL_NAME,
    api_key=GROQ_API_KEY,
    temperature=0.3
)

def writer_agent(state: dict) -> dict:
    facts_text = '\n'.join(state['verified_facts'])
    sources = [s['url'] for s in state['extracted_content']]
    sources_text = '\n'.join([f"{i+1}. {url}" for i, url in enumerate(sources)])

    prompt = f"""
    Write a comprehensive research report on: {state['topic']}

    Use these verified facts:
    {facts_text}

    Structure the report with these exact sections:

    ## Executive Summary
    ## Key Findings
    ## Detailed Analysis
    ## Current Landscape
    ## Challenges and Limitations
    ## Future Outlook
    ## Conclusion

    Write professionally with specific data and numbers where available.
    """

    response = llm.invoke(prompt)

    full_report = f"""# Research Report: {state['topic']}
---
*Generated by Agent Researcher | {len(state['extracted_content'])} sources analyzed*

{response.content}

---
## Sources
{sources_text}
"""

    return {**state, "final_report": full_report, "status": "complete"}